export const FETCH_CARD_REQUEST = 'FETCH_CARD_REQUEST';
export const FETCH_CARD_SUCCESS = 'FETCH_CARD_SUCCESS';
export const FETCH_CARD_FAILED = 'FETCH_CARD_FAILED';

export const SORT_POSTS_ASC = 'SORT_POSTS_ASC';
export const SORT_POSTS_DESC = 'SORT_POSTS_DESC';

export const SEARCH_CARDS = 'SEARCH_CARDS';